// Ce fichier est généré par npm run build:icons

export type IconName =
  | "accessible-filled"
  | "arrow-left"
  | "arrow-right"
  | "arrow-up"
  | "avatar"
  | "border-all"
  | "border-style"
  | "check-circled"
  | "current-location-outline"
  | "download"
  | "figma-logo"
  | "file-phone-outline"
  | "info-circled"
  | "instagram-logo"
  | "linkedin-logo"
  | "magnifying-glass"
  | "mail-outline"
  | "phone-filled"
  | "phone-outline"
  | "twitter-logo"
  | "watsapp"
  | "zoom-out";
